name: libhs
version: 0.4.0
maintainer: Philipp Dargel <chisui.pd@gmail.com>
license: MIT

ghc-options: -Wall

dependencies:
- base
- containers
- ghc-prim
- template-haskell
- deepseq
- hashable
- haskell-src-meta

tests:
  spec:
    main: test/Spec.hs
    dependencies:
    - libhs

library:
  source-dirs: src
  ghc-options: -Werror
  exposed-modules:
  - Std
  - Std.Basic
  - Std.BinOp
  - Std.Bool
  - Std.Cat
  - Std.Debug
  - Std.Either
  - Std.Extremum
  - Std.Fixed
  - Std.FreeGroup
  - Std.Generic
  - Std.Generic.Simple
  - Std.Group
  - Std.IfThenElse
  - Std.IO
  - Std.List
  - Std.Literal
  - Std.Maybe
  - Std.Ord
  - Std.Partial
  - Std.Quote
  - Std.Singleton
  - Std.Some
  - Std.Text
  - Std.Tuple
  - Std.TypeError
  - Std.Type
  - Std.Union
  - Std.Vec


default-extensions:
- NoImplicitPrelude
- NoStarIsType
# imports
- ImportQualifiedPost
- PackageImports
# syntax
- RebindableSyntax
- TupleSections
- ScopedTypeVariables
- TypeApplications
- LambdaCase
- InstanceSigs
# deriving
- StandaloneDeriving
- GeneralizedNewtypeDeriving
- DeriveGeneric
- DerivingVia
- DeriveDataTypeable
# type stuff
- TypeOperators
- TypeFamilies
- PolyKinds
- ConstraintKinds
- DataKinds
- MultiParamTypeClasses
- TypeSynonymInstances
- FlexibleInstances
- FlexibleContexts
- FunctionalDependencies
- QuantifiedConstraints
- RankNTypes
- GADTs
